services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"  
      - "50051:50051" 
    volumes:
      - ./weaviate_data:/var/lib/weaviate 
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      ENABLE_MODULES: 'text2vec-openai'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'weaviate'
      OPENAI_APIKEY: ${OPENAI_API_KEY:-}

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data 
    environment:
      POSTGRES_DB: mindseek_db
      POSTGRES_USER: mindseek_user
      POSTGRES_PASSWORD: password_test

volumes:
  weaviate_data:
  postgres_data: